module.exports = {
  apps: [
    {
      name: 'hypecrm-web',
      cwd: '/var/www/hypeCRM',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -H 0.0.0.0 -p 3434',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      min_uptime: '5s',
      max_restarts: 30,
      restart_delay: 2000,
      kill_timeout: 5000,
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'production',
        UNDICI_SOCKET_FAMILY: 'ipv4',
      },
    },
    {
      name: 'hypecrm-chat-scheduler',
      cwd: '/var/www/hypeCRM',
      script: 'node_modules/tsx/dist/cli.mjs',
      args: 'scripts/chat-scheduled-messages-worker.ts',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      min_uptime: '5s',
      max_restarts: 30,
      restart_delay: 2000,
      kill_timeout: 5000,
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'production',
        UNDICI_SOCKET_FAMILY: 'ipv4',
      },
    },
  ],
};
